/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vet_clinic_gui;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author Vince Gnodle
 */
public class CustomerMenu extends javax.swing.JFrame {
    
    protected static Clinic clinic;
    private Calendar calendar;
    private Owner current_owner;
    private Animal current_animal;
    private static final String ownerStorage = "Owner_Registry.csv";
    private static final String animalStorage = "Animal_Registry.csv";
    private ReadWrite ownerRW;
    private ReadWrite animalRW;
    /**
     * Creates new form CustomerMenu
     */
    public CustomerMenu() {
        
        initComponents();
         
        pnlPay.setVisible(false);
        LblNewCustTitle.setVisible(false);
        lblVerify.setVisible(false);
        btnSubmit.setVisible(false);
        LblEnterID.setVisible(false);
        PasswordCustID.setVisible(false);
        btnEnter.setVisible(false);
        
        
    }
    
    /**
     * Creates new form CustomerMenu
     * @param clinic the clinic of the operating system
     */
    public CustomerMenu(Clinic clinic) {
        this();
        CustomerMenu.clinic = clinic;
        ownerRW = new ReadWrite(CustomerMenu.clinic.registry, ownerStorage, current_owner);
        animalRW = new ReadWrite(CustomerMenu.clinic.registry, animalStorage,current_animal);
        
        ownerRW.readCSV();
        animalRW.readCSV();
    }
    /**
     * Creates and returns a new Animal patient
     * @param name
     * @param age
     * @param species
     * @param breed
     */
    public void addAnimal(String name, int age, String species, String breed){
        //creates and returns animal object using entered user info
        
        try{
            current_animal = new Animal(name, age, species, breed);
        
            //adds animal to animal registry
            clinic.registry.addPT(current_animal.getName(), current_animal); //adds animal to animal registry
            current_owner.setAnimal(current_animal);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getCause());
        }
        
    }
    
    /**
     * Method adds owner and animal customers to their respective registry and
     * assigns them to each other. 
     * @param userID owners user ID used to search for them in the registry
     * @param name
     * @param dob
     * @param phone
     */
    public void addOwner(String userID, String name, String dob, String phone){
        
        try{
            
            current_owner = new Owner(userID, name, dob, phone);

            clinic.registry.addCustomer(userID, current_owner);  //adds owner to owner registry
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getCause());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrpTreat = new javax.swing.ButtonGroup();
        btnGrpNeworExist = new javax.swing.ButtonGroup();
        tabPnlCustomer = new javax.swing.JTabbedPane();
        tabNewCust = new javax.swing.JPanel();
        LblNewCustTitle = new javax.swing.JLabel();
        LblPetSpecies = new javax.swing.JLabel();
        LblPetBreed = new javax.swing.JLabel();
        LblCustDOB = new javax.swing.JLabel();
        LblCustPhone = new javax.swing.JLabel();
        LblPetName = new javax.swing.JLabel();
        LblCustName = new javax.swing.JLabel();
        LblPetAge = new javax.swing.JLabel();
        TxtPetAge = new javax.swing.JTextField();
        TxtCustName = new javax.swing.JTextField();
        TxtCustDOB = new javax.swing.JTextField();
        TxtCustPhone = new javax.swing.JTextField();
        TxtPetName = new javax.swing.JTextField();
        TxtPetSpecies = new javax.swing.JTextField();
        TxtPetBreed = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        LblCustUserID = new javax.swing.JLabel();
        TxtCustUserID = new javax.swing.JTextField();
        btnEnter = new javax.swing.JButton();
        PasswordCustID = new javax.swing.JPasswordField();
        LblEnterID = new javax.swing.JLabel();
        lblVerify = new javax.swing.JLabel();
        pnlNeworExist = new javax.swing.JPanel();
        btnRdoNewCust = new javax.swing.JRadioButton();
        btnRdoExistCust = new javax.swing.JRadioButton();
        btnUpdate = new javax.swing.JButton();
        tabBilling = new javax.swing.JPanel();
        pnlCurrentBill = new javax.swing.JPanel();
        lblCurrentBill = new javax.swing.JLabel();
        TxtCurrentBill = new javax.swing.JTextField();
        btnPayBill = new javax.swing.JButton();
        pnlPay = new javax.swing.JPanel();
        lblDesired = new javax.swing.JLabel();
        TxtDesired = new javax.swing.JTextField();
        TxtStillOwed = new javax.swing.JTextField();
        lblStillOwed = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        tabSchedule = new javax.swing.JPanel();
        spinnerTime = new javax.swing.JSpinner();
        pnlTrtBtn = new javax.swing.JPanel();
        rdoBtnSurgery = new javax.swing.JRadioButton();
        rdoBtnGrooming = new javax.swing.JRadioButton();
        rdoBtnCheckup = new javax.swing.JRadioButton();
        lblSelectDate = new javax.swing.JLabel();
        lblSelectTreat = new javax.swing.JLabel();
        lblThenPush = new javax.swing.JLabel();
        btnEnterDate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Customer Menu");
        setBackground(new java.awt.Color(153, 153, 153));
        setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 480));
        setPreferredSize(new java.awt.Dimension(750, 480));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabPnlCustomer.setBackground(new java.awt.Color(153, 153, 153));
        tabPnlCustomer.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabPnlCustomer.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabPnlCustomer.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        tabPnlCustomer.setMinimumSize(new java.awt.Dimension(750, 480));
        tabPnlCustomer.setPreferredSize(new java.awt.Dimension(750, 480));

        tabNewCust.setBackground(new java.awt.Color(0, 0, 0));
        tabNewCust.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        tabNewCust.setMinimumSize(new java.awt.Dimension(600, 450));
        tabNewCust.setPreferredSize(new java.awt.Dimension(600, 450));
        tabNewCust.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblNewCustTitle.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 24)); // NOI18N
        LblNewCustTitle.setForeground(new java.awt.Color(204, 204, 204));
        LblNewCustTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblNewCustTitle.setText("Create new customer profile");
        LblNewCustTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LblNewCustTitle.setMaximumSize(new java.awt.Dimension(310, 28));
        LblNewCustTitle.setMinimumSize(new java.awt.Dimension(310, 28));
        LblNewCustTitle.setPreferredSize(new java.awt.Dimension(312, 28));
        tabNewCust.add(LblNewCustTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        LblPetSpecies.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetSpecies.setForeground(new java.awt.Color(204, 204, 204));
        LblPetSpecies.setText("Pet's Species (Dog, Cat, etc):");
        tabNewCust.add(LblPetSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));

        LblPetBreed.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetBreed.setForeground(new java.awt.Color(204, 204, 204));
        LblPetBreed.setText("Pet's Breed(if known):");
        tabNewCust.add(LblPetBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        LblCustDOB.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblCustDOB.setForeground(new java.awt.Color(204, 204, 204));
        LblCustDOB.setText("Date of Birth mm/dd/yyyy:");
        tabNewCust.add(LblCustDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        LblCustPhone.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblCustPhone.setForeground(new java.awt.Color(204, 204, 204));
        LblCustPhone.setText("Phone Number xxx-xxx-xxxx:");
        tabNewCust.add(LblCustPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        LblPetName.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetName.setForeground(new java.awt.Color(204, 204, 204));
        LblPetName.setText("Pet's Name:");
        tabNewCust.add(LblPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        LblCustName.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblCustName.setForeground(new java.awt.Color(204, 204, 204));
        LblCustName.setText("Name:");
        tabNewCust.add(LblCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        LblPetAge.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetAge.setForeground(new java.awt.Color(204, 204, 204));
        LblPetAge.setText("Pet's Age:");
        tabNewCust.add(LblPetAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        TxtPetAge.setBackground(new java.awt.Color(204, 255, 255));
        tabNewCust.add(TxtPetAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 30, -1));

        TxtCustName.setBackground(new java.awt.Color(204, 255, 255));
        tabNewCust.add(TxtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 140, -1));

        TxtCustDOB.setBackground(new java.awt.Color(204, 255, 255));
        tabNewCust.add(TxtCustDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 80, -1));

        TxtCustPhone.setBackground(new java.awt.Color(204, 255, 255));
        tabNewCust.add(TxtCustPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 90, -1));

        TxtPetName.setBackground(new java.awt.Color(204, 255, 255));
        tabNewCust.add(TxtPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 64, -1));

        TxtPetSpecies.setBackground(new java.awt.Color(204, 255, 255));
        tabNewCust.add(TxtPetSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 40, -1));

        TxtPetBreed.setBackground(new java.awt.Color(204, 255, 255));
        tabNewCust.add(TxtPetBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, 100, -1));

        btnSubmit.setBackground(new java.awt.Color(153, 153, 153));
        btnSubmit.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnSubmit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        tabNewCust.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 410, 110, -1));

        LblCustUserID.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblCustUserID.setForeground(new java.awt.Color(204, 204, 204));
        LblCustUserID.setText("Create userID");
        tabNewCust.add(LblCustUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        TxtCustUserID.setBackground(new java.awt.Color(204, 255, 255));
        tabNewCust.add(TxtCustUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 120, -1));

        btnEnter.setBackground(new java.awt.Color(153, 153, 153));
        btnEnter.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnEnter.setForeground(new java.awt.Color(255, 255, 255));
        btnEnter.setText("Enter");
        btnEnter.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });
        tabNewCust.add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 64, -1));

        PasswordCustID.setBackground(new java.awt.Color(204, 255, 255));
        PasswordCustID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabNewCust.add(PasswordCustID, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 64, -1));

        LblEnterID.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 18)); // NOI18N
        LblEnterID.setForeground(new java.awt.Color(204, 204, 204));
        LblEnterID.setText("Enter in User ID");
        LblEnterID.setPreferredSize(new java.awt.Dimension(280, 42));
        tabNewCust.add(LblEnterID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 140, 20));

        lblVerify.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 24)); // NOI18N
        lblVerify.setForeground(new java.awt.Color(204, 204, 204));
        lblVerify.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVerify.setText("Enter User Id Then Verify Info ");
        lblVerify.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVerify.setMaximumSize(new java.awt.Dimension(310, 28));
        lblVerify.setMinimumSize(new java.awt.Dimension(310, 28));
        lblVerify.setPreferredSize(new java.awt.Dimension(312, 28));
        tabNewCust.add(lblVerify, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 330, -1));

        pnlNeworExist.setBackground(new java.awt.Color(153, 153, 153));
        pnlNeworExist.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlNeworExist.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRdoNewCust.setBackground(new java.awt.Color(153, 153, 153));
        btnGrpNeworExist.add(btnRdoNewCust);
        btnRdoNewCust.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnRdoNewCust.setForeground(new java.awt.Color(255, 255, 255));
        btnRdoNewCust.setText("New Customer");
        btnRdoNewCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRdoNewCustActionPerformed(evt);
            }
        });
        pnlNeworExist.add(btnRdoNewCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, -1));

        btnRdoExistCust.setBackground(new java.awt.Color(153, 153, 153));
        btnGrpNeworExist.add(btnRdoExistCust);
        btnRdoExistCust.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnRdoExistCust.setForeground(new java.awt.Color(255, 255, 255));
        btnRdoExistCust.setText("Exist Customer");
        btnRdoExistCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRdoExistCustActionPerformed(evt);
            }
        });
        pnlNeworExist.add(btnRdoExistCust, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, -1));

        tabNewCust.add(pnlNeworExist, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 150, 100));

        btnUpdate.setBackground(new java.awt.Color(153, 153, 153));
        btnUpdate.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Info");
        btnUpdate.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        tabNewCust.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, -1));

        tabPnlCustomer.addTab("Personal Info", tabNewCust);

        tabBilling.setBackground(new java.awt.Color(0, 0, 0));
        tabBilling.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCurrentBill.setBackground(new java.awt.Color(153, 153, 153));
        pnlCurrentBill.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCurrentBill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCurrentBill.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblCurrentBill.setText("Current Bill:");
        pnlCurrentBill.add(lblCurrentBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        TxtCurrentBill.setBackground(new java.awt.Color(204, 255, 255));
        TxtCurrentBill.setBorder(null);
        TxtCurrentBill.setEnabled(false);
        pnlCurrentBill.add(TxtCurrentBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 64, 22));

        btnPayBill.setBackground(new java.awt.Color(204, 204, 204));
        btnPayBill.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnPayBill.setText("Pay Bill");
        btnPayBill.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnPayBill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPayBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayBillActionPerformed(evt);
            }
        });
        pnlCurrentBill.add(btnPayBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 70, -1));

        tabBilling.add(pnlCurrentBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 440, 100));

        pnlPay.setBackground(new java.awt.Color(153, 153, 153));
        pnlPay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDesired.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblDesired.setText("Desired Payment");
        pnlPay.add(lblDesired, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        TxtDesired.setBackground(new java.awt.Color(204, 255, 255));
        TxtDesired.setBorder(null);
        pnlPay.add(TxtDesired, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 17, 60, 22));

        TxtStillOwed.setBackground(new java.awt.Color(204, 255, 255));
        TxtStillOwed.setBorder(null);
        TxtStillOwed.setEnabled(false);
        pnlPay.add(TxtStillOwed, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 67, 60, 22));

        lblStillOwed.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        lblStillOwed.setText("Amount Still Owed:");
        pnlPay.add(lblStillOwed, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        btnPay.setBackground(new java.awt.Color(204, 204, 204));
        btnPay.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnPay.setText("Pay");
        btnPay.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnPay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        pnlPay.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 17, 70, -1));

        tabBilling.add(pnlPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 440, 110));

        tabPnlCustomer.addTab("Billing", tabBilling);

        tabSchedule.setBackground(new java.awt.Color(0, 0, 0));
        tabSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spinnerTime.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        spinnerTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1683566046126L), new java.util.Date(1735687800000L), java.util.Calendar.DAY_OF_MONTH));
        spinnerTime.setToolTipText("");
        spinnerTime.setBorder(null);
        tabSchedule.add(spinnerTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 300, 40));

        pnlTrtBtn.setBackground(new java.awt.Color(153, 153, 153));
        pnlTrtBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTrtBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdoBtnSurgery.setBackground(new java.awt.Color(153, 153, 153));
        btnGrpTreat.add(rdoBtnSurgery);
        rdoBtnSurgery.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        rdoBtnSurgery.setForeground(new java.awt.Color(255, 255, 255));
        rdoBtnSurgery.setText("Surgery");
        rdoBtnSurgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnSurgeryActionPerformed(evt);
            }
        });
        pnlTrtBtn.add(rdoBtnSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        rdoBtnGrooming.setBackground(new java.awt.Color(153, 153, 153));
        btnGrpTreat.add(rdoBtnGrooming);
        rdoBtnGrooming.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        rdoBtnGrooming.setForeground(new java.awt.Color(255, 255, 255));
        rdoBtnGrooming.setText("Grooming");
        rdoBtnGrooming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnGroomingActionPerformed(evt);
            }
        });
        pnlTrtBtn.add(rdoBtnGrooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        rdoBtnCheckup.setBackground(new java.awt.Color(153, 153, 153));
        btnGrpTreat.add(rdoBtnCheckup);
        rdoBtnCheckup.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        rdoBtnCheckup.setForeground(new java.awt.Color(255, 255, 255));
        rdoBtnCheckup.setText("Checkup");
        rdoBtnCheckup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnCheckupActionPerformed(evt);
            }
        });
        pnlTrtBtn.add(rdoBtnCheckup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        tabSchedule.add(pnlTrtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 130, 170));

        lblSelectDate.setBackground(new java.awt.Color(153, 153, 153));
        lblSelectDate.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblSelectDate.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectDate.setText("Select Date and Time ");
        lblSelectDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tabSchedule.add(lblSelectDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 250, 40));

        lblSelectTreat.setBackground(new java.awt.Color(153, 153, 153));
        lblSelectTreat.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblSelectTreat.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectTreat.setText("Select Treatment");
        tabSchedule.add(lblSelectTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 150, 30));

        lblThenPush.setBackground(new java.awt.Color(153, 153, 153));
        lblThenPush.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblThenPush.setForeground(new java.awt.Color(255, 255, 255));
        lblThenPush.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThenPush.setText("Then Push Enter");
        lblThenPush.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tabSchedule.add(lblThenPush, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 250, 40));

        btnEnterDate.setBackground(new java.awt.Color(153, 153, 153));
        btnEnterDate.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnEnterDate.setForeground(new java.awt.Color(255, 255, 255));
        btnEnterDate.setText("Enter");
        btnEnterDate.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnEnterDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterDateActionPerformed(evt);
            }
        });
        tabSchedule.add(btnEnterDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 64, -1));

        tabPnlCustomer.addTab("Schedule treatment", tabSchedule);

        getContentPane().add(tabPnlCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 490));

        setSize(new java.awt.Dimension(778, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        //use entered in userId to search for Customer and animal
        //populate bill
        try{
            current_owner = clinic.registry.searchByOwner(String.valueOf(PasswordCustID.getPassword()));

            if(current_owner != null){
                
                btnUpdate.setEnabled(true);
                TxtCustName.setText(current_owner.getName());
                TxtCustDOB.setText(current_owner.getDOB());
                TxtCustPhone.setText(current_owner.getPhoneNumber());
                TxtCurrentBill.setText(String.valueOf(current_owner.getBill()));
                
                TxtPetName.setText(current_animal.getName());
                TxtPetAge.setText(String.valueOf(current_animal.getAge()));
                TxtPetSpecies.setText(current_animal.getSpecies());
                TxtPetBreed.setText(String.valueOf(current_animal.getBreed()));
                
                PasswordCustID.setText("");
                
                JOptionPane.showMessageDialog(this,"Profile found, ensure info is correct");
            }
        }

        catch(HeadlessException e){

            JOptionPane.showMessageDialog(this,"Profile not found, check your info and try again.");
        }

    }//GEN-LAST:event_btnEnterActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

        // Get the values
        String userID = TxtCustUserID.getText();
        String owner_name = TxtCustName.getText();
        String DOB = TxtCustDOB.getText();
        String phone = TxtCustPhone.getText();
        
        String animal_name = TxtPetName.getText();
        int animal_age = Integer.parseInt(TxtPetAge.getText());
        String species = TxtPetSpecies.getText();
        String breed = TxtPetBreed.getText();
        
        //addCustomer(userID, owner_name, DOB, phone, animal_name, animal_age, species, breed);
        addOwner(userID, owner_name, DOB, phone);
        addAnimal(animal_name, animal_age, species, breed);
        
        
        
        TxtCustUserID.setText("");
        TxtCustName.setText("");
        TxtCustDOB.setText("");
        TxtCustPhone.setText("");
        
        TxtPetName.setText("");
        TxtPetAge.setText("");
        TxtPetSpecies.setText("");
        TxtPetBreed.setText("");
        //set animal text
        
        ownerRW.updateCSV();
        animalRW.updateCSV();
        
        pnlCurrentBill.setVisible(true);
        
        JOptionPane.showMessageDialog(this,"Profile successfully created");
        
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnPayBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayBillActionPerformed
        pnlPay.setVisible(true);
        
    }//GEN-LAST:event_btnPayBillActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        Transaction billPay = new Transaction();
        billPay.billPaid(current_owner, current_owner.getBill(), Integer.parseInt(TxtDesired.getText()));
        
        TxtStillOwed.setText(String.valueOf(current_owner.getBill()));
    }//GEN-LAST:event_btnPayActionPerformed

    private void rdoBtnGroomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnGroomingActionPerformed
        calendar = clinic.groomingCalendar;
    }//GEN-LAST:event_rdoBtnGroomingActionPerformed

    private void rdoBtnSurgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnSurgeryActionPerformed
        calendar = clinic.surgeryCalendar;
    }//GEN-LAST:event_rdoBtnSurgeryActionPerformed

    private void rdoBtnCheckupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnCheckupActionPerformed
        calendar = clinic.checkupCalendar;
    }//GEN-LAST:event_rdoBtnCheckupActionPerformed

    private void btnRdoNewCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRdoNewCustActionPerformed
        
        //hides existing customer components
        lblVerify.setVisible(false);
        LblEnterID.setVisible(false);
        PasswordCustID.setVisible(false);
        btnEnter.setVisible(false);
        btnUpdate.setVisible(false);
        
        //shows new customer components
        LblNewCustTitle.setVisible(true);
        btnSubmit.setVisible(true);
    }//GEN-LAST:event_btnRdoNewCustActionPerformed

    private void btnRdoExistCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRdoExistCustActionPerformed
        //hides new customer components
        LblNewCustTitle.setVisible(false);
        btnSubmit.setVisible(false); 
        
        //shows existing customer components
        btnUpdate.setVisible(true);
        lblVerify.setVisible(true);
        LblEnterID.setVisible(true);
        PasswordCustID.setVisible(true);
        btnEnter.setVisible(true);
    }//GEN-LAST:event_btnRdoExistCustActionPerformed

    private void btnEnterDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterDateActionPerformed
        String date = (String.valueOf(spinnerTime.getValue()));
        System.out.println(date);
        String[] MDY = date.split(" ");
        String month = MDY[1];
        int day = Integer.parseInt(MDY[2]);
        String time = MDY[3];
        String[] HM = time.split(":");
        int hour = Integer.parseInt(HM[0]);
        
        int min = Integer.parseInt(HM[1]);
//        System.out.println(month);
//        System.out.println(day);
//        System.out.println(time);
//        System.out.println(hour);
//        System.out.println(min);
       
        if(calendar.Schedule(current_animal, month, day, hour)){
            JOptionPane.showMessageDialog(this,"Your appointment was successfully scheduled!");
        }
        else{
            JOptionPane.showMessageDialog(this,"Appointment not available, try another date or time");
        }
    }//GEN-LAST:event_btnEnterDateActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // Creates a new customer using the SAME id, with any new
        // name, age, salary
       
        String userID = TxtCustUserID.getText();
        String owner_name = TxtCustName.getText();
        String DOB = TxtCustDOB.getText();
        String phone = TxtCustPhone.getText();
        
        String animal_name = TxtPetName.getText();
        int animal_age = Integer.parseInt(TxtPetAge.getText());
        String species = TxtPetSpecies.getText();
        String breed = TxtPetBreed.getText();
        
        // Updates the value for that id
        addOwner(userID, owner_name, DOB, phone);
        ownerRW.updateCSV();
        
        addAnimal(animal_name, animal_age, species, breed);
        animalRW.updateCSV();
        
        
        JOptionPane.showMessageDialog(this, "Information Updated");
        
        TxtCustUserID.setText("");
        TxtCustName.setText("");
        TxtCustDOB.setText("");
        TxtCustPhone.setText("");
        
        TxtPetName.setText("");
        TxtPetAge.setText("");
        TxtPetSpecies.setText("");
        TxtPetBreed.setText("");
        //set animal text
        
        btnUpdate.setEnabled(false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Dark Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new CustomerMenu(clinic).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCustDOB;
    private javax.swing.JLabel LblCustName;
    private javax.swing.JLabel LblCustPhone;
    private javax.swing.JLabel LblCustUserID;
    protected javax.swing.JLabel LblEnterID;
    protected javax.swing.JLabel LblNewCustTitle;
    private javax.swing.JLabel LblPetAge;
    private javax.swing.JLabel LblPetBreed;
    private javax.swing.JLabel LblPetName;
    private javax.swing.JLabel LblPetSpecies;
    protected javax.swing.JPasswordField PasswordCustID;
    private javax.swing.JTextField TxtCurrentBill;
    private javax.swing.JTextField TxtCustDOB;
    private javax.swing.JTextField TxtCustName;
    private javax.swing.JTextField TxtCustPhone;
    private javax.swing.JTextField TxtCustUserID;
    private javax.swing.JTextField TxtDesired;
    private javax.swing.JTextField TxtPetAge;
    private javax.swing.JTextField TxtPetBreed;
    private javax.swing.JTextField TxtPetName;
    private javax.swing.JTextField TxtPetSpecies;
    private javax.swing.JTextField TxtStillOwed;
    protected javax.swing.JButton btnEnter;
    protected javax.swing.JButton btnEnterDate;
    private javax.swing.ButtonGroup btnGrpNeworExist;
    private javax.swing.ButtonGroup btnGrpTreat;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPayBill;
    private javax.swing.JRadioButton btnRdoExistCust;
    private javax.swing.JRadioButton btnRdoNewCust;
    protected javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel lblCurrentBill;
    private javax.swing.JLabel lblDesired;
    private javax.swing.JLabel lblSelectDate;
    private javax.swing.JLabel lblSelectTreat;
    private javax.swing.JLabel lblStillOwed;
    private javax.swing.JLabel lblThenPush;
    protected javax.swing.JLabel lblVerify;
    private javax.swing.JPanel pnlCurrentBill;
    private javax.swing.JPanel pnlNeworExist;
    private javax.swing.JPanel pnlPay;
    private javax.swing.JPanel pnlTrtBtn;
    private javax.swing.JRadioButton rdoBtnCheckup;
    private javax.swing.JRadioButton rdoBtnGrooming;
    private javax.swing.JRadioButton rdoBtnSurgery;
    private javax.swing.JSpinner spinnerTime;
    private javax.swing.JPanel tabBilling;
    private javax.swing.JPanel tabNewCust;
    private javax.swing.JTabbedPane tabPnlCustomer;
    private javax.swing.JPanel tabSchedule;
    // End of variables declaration//GEN-END:variables
}
