/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vet_clinic_gui;

import javax.swing.JOptionPane;

/**
 *
 * @author Vince Gnodle
 */
public class EmployeeMenu extends javax.swing.JFrame {

    private static Clinic clinic;
    private Calendar calendar;
    private Owner current_owner;
    private Animal current_animal;
    private static final String ownerStorage = "Owner_Registry.csv";
    private static final String animalStorage = "Animal_Registry.csv";
    private ReadWrite ownerRW;
    private ReadWrite animalRW;
    
    /**
     * Creates new form EmployeeMenu
     */
    public EmployeeMenu() {
        initComponents();
        
        
//        LblNewCustTitle.setVisible(false);
//        lblVerify.setVisible(false);
//        btnSubmit.setVisible(false);
//        LblEnterID.setVisible(false);
//        PasswordCustID.setVisible(false);
//        btnEnter.setVisible(false);
        
        
        //disable all buttons and text fields until password input
    }

    /**
     * Creates new form EmployeeMenu
     * @param clinic
     */
    public EmployeeMenu(Clinic clinic) {
        this();
        EmployeeMenu.clinic = clinic;
        ownerRW = new ReadWrite(EmployeeMenu.clinic.registry, ownerStorage, current_owner);
        animalRW = new ReadWrite(EmployeeMenu.clinic.registry, animalStorage, current_animal);
        
        ownerRW.readCSV();
        animalRW.readCSV();
        pnlPay.setVisible(false);
        LblUserID.setVisible(false);
        PasswordUserID.setVisible(false);
        btnEnterUserID.setVisible(false);
        
        tabBilling.setEnabled(false);
        tabInventory.setEnabled(false);
        tabPlaceAnimal.setEnabled(false);
        tabReport.setEnabled(false);
        tabSchedule.setEnabled(false);
        tabUpdatePt.setEnabled(false);
                        
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupSend = new javax.swing.ButtonGroup();
        buttonGroupAptOption = new javax.swing.ButtonGroup();
        buttonGroupCalendar = new javax.swing.ButtonGroup();
        buttonGroupUpdate = new javax.swing.ButtonGroup();
        tabPanelEmp = new javax.swing.JTabbedPane();
        tabSignIn = new javax.swing.JPanel();
        LblPin = new javax.swing.JLabel();
        PasswordEmployee = new javax.swing.JPasswordField();
        btnEnterPin = new javax.swing.JButton();
        LblUserID = new javax.swing.JLabel();
        PasswordUserID = new javax.swing.JPasswordField();
        btnEnterUserID = new javax.swing.JButton();
        tabBilling = new javax.swing.JPanel();
        pnlCurrentBill = new javax.swing.JPanel();
        lblCurrentBill = new javax.swing.JLabel();
        TxtCurrentBill = new javax.swing.JTextField();
        btnPayBill = new javax.swing.JButton();
        pnlPay = new javax.swing.JPanel();
        lblDesired = new javax.swing.JLabel();
        TxtDesired = new javax.swing.JTextField();
        TxtStillOwed = new javax.swing.JTextField();
        lblStillOwed = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        tabReport = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtAreaReport = new javax.swing.JTextArea();
        btnGenerate = new javax.swing.JButton();
        tabInventory = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TxtAreaInventory = new javax.swing.JTextArea();
        PnlOrderMore = new javax.swing.JPanel();
        LblMedications = new javax.swing.JLabel();
        LblOffice = new javax.swing.JLabel();
        LblMedSupply = new javax.swing.JLabel();
        LblGrooming = new javax.swing.JLabel();
        spinnerGroom = new javax.swing.JSpinner();
        spinnerMeds = new javax.swing.JSpinner();
        spinnerOffice = new javax.swing.JSpinner();
        spinnerMedSupply = new javax.swing.JSpinner();
        btnSubmitGroom = new javax.swing.JButton();
        btnSubmitMeds = new javax.swing.JButton();
        btnSubmitOffice = new javax.swing.JButton();
        btnSubmitMedSupply = new javax.swing.JButton();
        btnCheckInventory = new javax.swing.JButton();
        LblOrder = new javax.swing.JLabel();
        tabUpdatePt = new javax.swing.JPanel();
        pnlUpdateOwner = new javax.swing.JPanel();
        LblCustName = new javax.swing.JLabel();
        TxtCustName = new javax.swing.JTextField();
        LblCustUserID = new javax.swing.JLabel();
        TxtCustUserID = new javax.swing.JTextField();
        LblCustDOB = new javax.swing.JLabel();
        TxtCustDOB = new javax.swing.JTextField();
        LblCustPhone = new javax.swing.JLabel();
        TxtCustPhone = new javax.swing.JTextField();
        btnUpdateOwner = new javax.swing.JButton();
        LblPetName = new javax.swing.JLabel();
        TxtPetName = new javax.swing.JTextField();
        LblPetSpecies = new javax.swing.JLabel();
        TxtPetSpecies = new javax.swing.JTextField();
        LblPetBreed = new javax.swing.JLabel();
        TxtPetBreed = new javax.swing.JTextField();
        LblPetAge = new javax.swing.JLabel();
        TxtPetAge = new javax.swing.JTextField();
        pnlAddAnimalInfo = new javax.swing.JPanel();
        LblPetAllergies = new javax.swing.JLabel();
        TxtPetAllergies = new javax.swing.JTextField();
        LblPetMeds = new javax.swing.JLabel();
        TxtPetMeds = new javax.swing.JTextField();
        LblPetNotes = new javax.swing.JLabel();
        TxtPetNotes = new javax.swing.JTextField();
        btnAddNotes = new javax.swing.JButton();
        btnAddAllergies = new javax.swing.JButton();
        btnAddMeds = new javax.swing.JButton();
        tabSchedule = new javax.swing.JPanel();
        spinnerTime = new javax.swing.JSpinner();
        pnlTrtBtn = new javax.swing.JPanel();
        rdoBtnSurgery = new javax.swing.JRadioButton();
        rdoBtnGrooming = new javax.swing.JRadioButton();
        rdoBtnCheckup = new javax.swing.JRadioButton();
        lblSelectDate = new javax.swing.JLabel();
        lblSelectTreat = new javax.swing.JLabel();
        lblThenPush = new javax.swing.JLabel();
        btnEnterTime = new javax.swing.JButton();
        pnlScheduleorCancel = new javax.swing.JPanel();
        jCheckBoxCancel = new javax.swing.JCheckBox();
        jCheckBoxSchedule = new javax.swing.JCheckBox();
        lblSelectAptOption = new javax.swing.JLabel();
        tabPlaceAnimal = new javax.swing.JPanel();
        LblWhereSending = new javax.swing.JLabel();
        pnlPlacePet = new javax.swing.JPanel();
        rdoBtnSendSurgery = new javax.swing.JRadioButton();
        rdoBtnSendGrooming = new javax.swing.JRadioButton();
        rdoBtnSendWaiting = new javax.swing.JRadioButton();
        rdoBtnSendCheckup = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(750, 500));

        tabPanelEmp.setBackground(new java.awt.Color(153, 153, 153));
        tabPanelEmp.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        tabPanelEmp.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        tabPanelEmp.setToolTipText("");
        tabPanelEmp.setAutoscrolls(true);
        tabPanelEmp.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        tabPanelEmp.setPreferredSize(new java.awt.Dimension(775, 480));

        tabSignIn.setBackground(new java.awt.Color(0, 0, 0));
        tabSignIn.setForeground(new java.awt.Color(204, 204, 204));
        tabSignIn.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        tabSignIn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblPin.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36)); // NOI18N
        LblPin.setForeground(new java.awt.Color(204, 204, 204));
        LblPin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblPin.setText("Enter in Your Pin");
        LblPin.setPreferredSize(new java.awt.Dimension(280, 42));
        tabSignIn.add(LblPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 390, 100));

        PasswordEmployee.setBackground(new java.awt.Color(204, 255, 255));
        PasswordEmployee.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabSignIn.add(PasswordEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 120, 40));

        btnEnterPin.setBackground(new java.awt.Color(153, 153, 153));
        btnEnterPin.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnEnterPin.setForeground(new java.awt.Color(255, 255, 255));
        btnEnterPin.setText("Enter");
        btnEnterPin.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnEnterPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterPinActionPerformed(evt);
            }
        });
        tabSignIn.add(btnEnterPin, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 120, 40));

        LblUserID.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36)); // NOI18N
        LblUserID.setForeground(new java.awt.Color(204, 204, 204));
        LblUserID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblUserID.setText("Search for User ID");
        LblUserID.setPreferredSize(new java.awt.Dimension(280, 42));
        tabSignIn.add(LblUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 390, 100));

        PasswordUserID.setBackground(new java.awt.Color(204, 255, 255));
        PasswordUserID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tabSignIn.add(PasswordUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 120, 40));

        btnEnterUserID.setBackground(new java.awt.Color(153, 153, 153));
        btnEnterUserID.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnEnterUserID.setForeground(new java.awt.Color(255, 255, 255));
        btnEnterUserID.setText("Enter");
        btnEnterUserID.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnEnterUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterUserIDActionPerformed(evt);
            }
        });
        tabSignIn.add(btnEnterUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 120, 40));

        tabPanelEmp.addTab("Enter Pin", tabSignIn);

        tabBilling.setBackground(new java.awt.Color(0, 0, 0));
        tabBilling.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlCurrentBill.setBackground(new java.awt.Color(153, 153, 153));
        pnlCurrentBill.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlCurrentBill.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCurrentBill.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblCurrentBill.setText("Current Bill:");
        pnlCurrentBill.add(lblCurrentBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 56, 100, 30));

        TxtCurrentBill.setBackground(new java.awt.Color(204, 255, 255));
        TxtCurrentBill.setBorder(null);
        TxtCurrentBill.setEnabled(false);
        pnlCurrentBill.add(TxtCurrentBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 90, 40));

        btnPayBill.setBackground(new java.awt.Color(204, 204, 204));
        btnPayBill.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnPayBill.setText("Pay Bill");
        btnPayBill.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnPayBill.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPayBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayBillActionPerformed(evt);
            }
        });
        pnlCurrentBill.add(btnPayBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, 40));

        tabBilling.add(pnlCurrentBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 570, 160));

        pnlPay.setBackground(new java.awt.Color(153, 153, 153));
        pnlPay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPay.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDesired.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblDesired.setText("Desired Payment");
        pnlPay.add(lblDesired, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 170, 30));

        TxtDesired.setBackground(new java.awt.Color(204, 255, 255));
        TxtDesired.setBorder(null);
        pnlPay.add(TxtDesired, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 90, 40));

        TxtStillOwed.setBackground(new java.awt.Color(204, 255, 255));
        TxtStillOwed.setBorder(null);
        TxtStillOwed.setEnabled(false);
        TxtStillOwed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtStillOwedActionPerformed(evt);
            }
        });
        pnlPay.add(TxtStillOwed, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 90, 40));

        lblStillOwed.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblStillOwed.setText("Amount Still Owed:");
        pnlPay.add(lblStillOwed, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 180, 30));

        btnPay.setBackground(new java.awt.Color(204, 204, 204));
        btnPay.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnPay.setText("Pay");
        btnPay.setBorder(javax.swing.BorderFactory.createCompoundBorder(new javax.swing.border.MatteBorder(null), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnPay.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        pnlPay.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, 90, 40));

        tabBilling.add(pnlPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 570, 170));

        tabPanelEmp.addTab("Billing", tabBilling);

        tabReport.setBackground(new java.awt.Color(0, 0, 0));
        tabReport.setForeground(new java.awt.Color(255, 255, 255));
        tabReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtAreaReport.setBackground(new java.awt.Color(204, 255, 255));
        TxtAreaReport.setColumns(20);
        TxtAreaReport.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        TxtAreaReport.setRows(5);
        TxtAreaReport.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TxtAreaReport.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtAreaReport.setEnabled(false);
        jScrollPane1.setViewportView(TxtAreaReport);

        tabReport.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 126, 660, 460));

        btnGenerate.setBackground(new java.awt.Color(153, 153, 153));
        btnGenerate.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 30)); // NOI18N
        btnGenerate.setText("Generate Report");
        btnGenerate.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });
        tabReport.add(btnGenerate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 290, 60));

        tabPanelEmp.addTab("Generate Report", tabReport);

        tabInventory.setBackground(new java.awt.Color(0, 0, 0));
        tabInventory.setMinimumSize(new java.awt.Dimension(614, 490));
        tabInventory.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TxtAreaInventory.setBackground(new java.awt.Color(204, 255, 255));
        TxtAreaInventory.setColumns(20);
        TxtAreaInventory.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        TxtAreaInventory.setRows(5);
        TxtAreaInventory.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TxtAreaInventory.setEnabled(false);
        jScrollPane2.setViewportView(TxtAreaInventory);

        tabInventory.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 530, 190));

        PnlOrderMore.setBackground(new java.awt.Color(204, 204, 204));
        PnlOrderMore.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        PnlOrderMore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblMedications.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblMedications.setText("Medications");
        PnlOrderMore.add(LblMedications, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 30));

        LblOffice.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblOffice.setText("Office Supply");
        PnlOrderMore.add(LblOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 110, 30));

        LblMedSupply.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblMedSupply.setText("Medical Supply");
        PnlOrderMore.add(LblMedSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 120, 30));

        LblGrooming.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblGrooming.setText("Grooming Products");
        PnlOrderMore.add(LblGrooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 30));

        spinnerGroom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PnlOrderMore.add(spinnerGroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 90, 30));

        spinnerMeds.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PnlOrderMore.add(spinnerMeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 90, 30));

        spinnerOffice.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PnlOrderMore.add(spinnerOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 90, 30));

        spinnerMedSupply.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        PnlOrderMore.add(spinnerMedSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 90, 30));

        btnSubmitGroom.setBackground(new java.awt.Color(153, 153, 153));
        btnSubmitGroom.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnSubmitGroom.setText("Submit");
        btnSubmitGroom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSubmitGroom.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubmitGroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitGroomActionPerformed(evt);
            }
        });
        PnlOrderMore.add(btnSubmitGroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 80, 30));

        btnSubmitMeds.setBackground(new java.awt.Color(153, 153, 153));
        btnSubmitMeds.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnSubmitMeds.setText("Submit");
        btnSubmitMeds.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSubmitMeds.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubmitMeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMedsActionPerformed(evt);
            }
        });
        PnlOrderMore.add(btnSubmitMeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 80, 30));

        btnSubmitOffice.setBackground(new java.awt.Color(153, 153, 153));
        btnSubmitOffice.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnSubmitOffice.setText("Submit");
        btnSubmitOffice.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSubmitOffice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubmitOffice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitOfficeActionPerformed(evt);
            }
        });
        PnlOrderMore.add(btnSubmitOffice, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 80, 30));

        btnSubmitMedSupply.setBackground(new java.awt.Color(153, 153, 153));
        btnSubmitMedSupply.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        btnSubmitMedSupply.setText("Submit");
        btnSubmitMedSupply.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnSubmitMedSupply.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSubmitMedSupply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitMedSupplyActionPerformed(evt);
            }
        });
        PnlOrderMore.add(btnSubmitMedSupply, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 80, 30));

        tabInventory.add(PnlOrderMore, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 540, 220));

        btnCheckInventory.setBackground(new java.awt.Color(153, 153, 153));
        btnCheckInventory.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        btnCheckInventory.setText("Check Inventory");
        btnCheckInventory.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCheckInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckInventoryActionPerformed(evt);
            }
        });
        tabInventory.add(btnCheckInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 340, 70));

        LblOrder.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        LblOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblOrder.setText("Order Supplies");
        tabInventory.add(LblOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 230, 260, -1));

        tabPanelEmp.addTab("Inventory", tabInventory);

        tabUpdatePt.setBackground(new java.awt.Color(0, 0, 0));
        tabUpdatePt.setPreferredSize(new java.awt.Dimension(614, 470));
        tabUpdatePt.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUpdateOwner.setBackground(new java.awt.Color(204, 204, 204));
        pnlUpdateOwner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlUpdateOwner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblCustName.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblCustName.setText("Name:");
        pnlUpdateOwner.add(LblCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 30));

        TxtCustName.setBackground(new java.awt.Color(204, 255, 255));
        TxtCustName.setFont(TxtCustName.getFont().deriveFont(TxtCustName.getFont().getSize()+6f));
        pnlUpdateOwner.add(TxtCustName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 160, 30));

        LblCustUserID.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblCustUserID.setText("Create userID");
        pnlUpdateOwner.add(LblCustUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 30));

        TxtCustUserID.setBackground(new java.awt.Color(204, 255, 255));
        TxtCustUserID.setFont(TxtCustUserID.getFont().deriveFont(TxtCustUserID.getFont().getSize()+6f));
        pnlUpdateOwner.add(TxtCustUserID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 140, 30));

        LblCustDOB.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblCustDOB.setText("Date of Birth mm/dd/yyyy:");
        pnlUpdateOwner.add(LblCustDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 30));

        TxtCustDOB.setBackground(new java.awt.Color(204, 255, 255));
        TxtCustDOB.setFont(TxtCustDOB.getFont().deriveFont(TxtCustDOB.getFont().getSize()+6f));
        pnlUpdateOwner.add(TxtCustDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 100, 30));

        LblCustPhone.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblCustPhone.setText("Phone Number xxx-xxx-xxxx:");
        pnlUpdateOwner.add(LblCustPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 200, 30));

        TxtCustPhone.setBackground(new java.awt.Color(204, 255, 255));
        TxtCustPhone.setFont(TxtCustPhone.getFont().deriveFont(TxtCustPhone.getFont().getSize()+6f));
        pnlUpdateOwner.add(TxtCustPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 100, 30));

        btnUpdateOwner.setBackground(new java.awt.Color(153, 153, 153));
        btnUpdateOwner.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnUpdateOwner.setText("Update");
        btnUpdateOwner.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnUpdateOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOwnerActionPerformed(evt);
            }
        });
        pnlUpdateOwner.add(btnUpdateOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 130, 30));

        LblPetName.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetName.setText("Pet's Name:");
        pnlUpdateOwner.add(LblPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, -1, 30));

        TxtPetName.setBackground(new java.awt.Color(204, 255, 255));
        TxtPetName.setFont(TxtPetName.getFont().deriveFont(TxtPetName.getFont().getSize()+6f));
        pnlUpdateOwner.add(TxtPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 130, 30));

        LblPetSpecies.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetSpecies.setText("Pet's Species (Dog, Cat, etc):");
        pnlUpdateOwner.add(LblPetSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, 30));

        TxtPetSpecies.setBackground(new java.awt.Color(204, 255, 255));
        TxtPetSpecies.setFont(TxtPetSpecies.getFont().deriveFont(TxtPetSpecies.getFont().getSize()+6f));
        pnlUpdateOwner.add(TxtPetSpecies, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 70, 100, 30));

        LblPetBreed.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetBreed.setText("Pet's Breed(if known):");
        pnlUpdateOwner.add(LblPetBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, 30));

        TxtPetBreed.setBackground(new java.awt.Color(204, 255, 255));
        TxtPetBreed.setFont(TxtPetBreed.getFont().deriveFont(TxtPetBreed.getFont().getSize()+6f));
        pnlUpdateOwner.add(TxtPetBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 160, 30));

        LblPetAge.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetAge.setText("Pet's Age:");
        pnlUpdateOwner.add(LblPetAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, -1, 30));

        TxtPetAge.setBackground(new java.awt.Color(204, 255, 255));
        TxtPetAge.setFont(TxtPetAge.getFont().deriveFont(TxtPetAge.getFont().getSize()+6f));
        pnlUpdateOwner.add(TxtPetAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, 90, 30));

        tabUpdatePt.add(pnlUpdateOwner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 300));

        pnlAddAnimalInfo.setBackground(new java.awt.Color(204, 204, 204));
        pnlAddAnimalInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlAddAnimalInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblPetAllergies.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetAllergies.setText("Pet's Allergies:");
        pnlAddAnimalInfo.add(LblPetAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, 30));

        TxtPetAllergies.setBackground(new java.awt.Color(204, 255, 255));
        TxtPetAllergies.setFont(TxtPetAllergies.getFont().deriveFont(TxtPetAllergies.getFont().getSize()+6f));
        pnlAddAnimalInfo.add(TxtPetAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 430, 30));

        LblPetMeds.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetMeds.setText("Pet's Medications:");
        pnlAddAnimalInfo.add(LblPetMeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 30));

        TxtPetMeds.setBackground(new java.awt.Color(204, 255, 255));
        TxtPetMeds.setFont(TxtPetMeds.getFont().deriveFont(TxtPetMeds.getFont().getSize()+6f));
        pnlAddAnimalInfo.add(TxtPetMeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 430, 30));

        LblPetNotes.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        LblPetNotes.setText("Pet's Dr Notes");
        pnlAddAnimalInfo.add(LblPetNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, 30));

        TxtPetNotes.setBackground(new java.awt.Color(204, 255, 255));
        TxtPetNotes.setFont(TxtPetNotes.getFont().deriveFont(TxtPetNotes.getFont().getSize()+6f));
        pnlAddAnimalInfo.add(TxtPetNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 430, 30));

        btnAddNotes.setBackground(new java.awt.Color(153, 153, 153));
        btnAddNotes.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnAddNotes.setText("Add");
        btnAddNotes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAddNotes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNotesActionPerformed(evt);
            }
        });
        pnlAddAnimalInfo.add(btnAddNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 100, 30));

        btnAddAllergies.setBackground(new java.awt.Color(153, 153, 153));
        btnAddAllergies.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnAddAllergies.setText("Add");
        btnAddAllergies.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAddAllergies.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddAllergies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAllergiesActionPerformed(evt);
            }
        });
        pnlAddAnimalInfo.add(btnAddAllergies, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 100, 30));

        btnAddMeds.setBackground(new java.awt.Color(153, 153, 153));
        btnAddMeds.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        btnAddMeds.setText("Add");
        btnAddMeds.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnAddMeds.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAddMeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMedsActionPerformed(evt);
            }
        });
        pnlAddAnimalInfo.add(btnAddMeds, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 100, 30));

        tabUpdatePt.add(pnlAddAnimalInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 730, 190));

        tabPanelEmp.addTab("Update Pt. Info", tabUpdatePt);

        tabSchedule.setBackground(new java.awt.Color(0, 0, 0));
        tabSchedule.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        spinnerTime.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        spinnerTime.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(1683566046126L), new java.util.Date(1704065400000L), java.util.Calendar.DAY_OF_MONTH));
        spinnerTime.setToolTipText("");
        spinnerTime.setBorder(null);
        tabSchedule.add(spinnerTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 300, 40));

        pnlTrtBtn.setBackground(new java.awt.Color(153, 153, 153));
        pnlTrtBtn.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlTrtBtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdoBtnSurgery.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupCalendar.add(rdoBtnSurgery);
        rdoBtnSurgery.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        rdoBtnSurgery.setForeground(new java.awt.Color(255, 255, 255));
        rdoBtnSurgery.setText("Surgery");
        rdoBtnSurgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnSurgeryActionPerformed(evt);
            }
        });
        pnlTrtBtn.add(rdoBtnSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        rdoBtnGrooming.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupCalendar.add(rdoBtnGrooming);
        rdoBtnGrooming.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        rdoBtnGrooming.setForeground(new java.awt.Color(255, 255, 255));
        rdoBtnGrooming.setText("Grooming");
        rdoBtnGrooming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnGroomingActionPerformed(evt);
            }
        });
        pnlTrtBtn.add(rdoBtnGrooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        rdoBtnCheckup.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupCalendar.add(rdoBtnCheckup);
        rdoBtnCheckup.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 14)); // NOI18N
        rdoBtnCheckup.setForeground(new java.awt.Color(255, 255, 255));
        rdoBtnCheckup.setText("Checkup");
        rdoBtnCheckup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnCheckupActionPerformed(evt);
            }
        });
        pnlTrtBtn.add(rdoBtnCheckup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        tabSchedule.add(pnlTrtBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 130, 170));

        lblSelectDate.setBackground(new java.awt.Color(153, 153, 153));
        lblSelectDate.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblSelectDate.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectDate.setText("Select Date and Time ");
        lblSelectDate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tabSchedule.add(lblSelectDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 250, 40));

        lblSelectTreat.setBackground(new java.awt.Color(153, 153, 153));
        lblSelectTreat.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblSelectTreat.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectTreat.setText("Select Treatment");
        tabSchedule.add(lblSelectTreat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 150, 30));

        lblThenPush.setBackground(new java.awt.Color(153, 153, 153));
        lblThenPush.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        lblThenPush.setForeground(new java.awt.Color(255, 255, 255));
        lblThenPush.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThenPush.setText("Then Push Enter");
        lblThenPush.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tabSchedule.add(lblThenPush, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 250, 40));

        btnEnterTime.setBackground(new java.awt.Color(153, 153, 153));
        btnEnterTime.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        btnEnterTime.setForeground(new java.awt.Color(255, 255, 255));
        btnEnterTime.setText("Enter");
        btnEnterTime.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        btnEnterTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterTimeActionPerformed(evt);
            }
        });
        tabSchedule.add(btnEnterTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 64, -1));

        pnlScheduleorCancel.setBackground(new java.awt.Color(153, 153, 153));
        pnlScheduleorCancel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlScheduleorCancel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroupAptOption.add(jCheckBoxCancel);
        jCheckBoxCancel.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jCheckBoxCancel.setText("Cancel");
        pnlScheduleorCancel.add(jCheckBoxCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        buttonGroupAptOption.add(jCheckBoxSchedule);
        jCheckBoxSchedule.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 12)); // NOI18N
        jCheckBoxSchedule.setText("Schedule");
        pnlScheduleorCancel.add(jCheckBoxSchedule, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        tabSchedule.add(pnlScheduleorCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 130, 110));

        lblSelectAptOption.setBackground(new java.awt.Color(153, 153, 153));
        lblSelectAptOption.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        lblSelectAptOption.setForeground(new java.awt.Color(255, 255, 255));
        lblSelectAptOption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSelectAptOption.setText("Select Appointment Option");
        tabSchedule.add(lblSelectAptOption, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 230, 30));

        tabPanelEmp.addTab("Schedule treatment", tabSchedule);

        tabPlaceAnimal.setBackground(new java.awt.Color(0, 0, 0));
        tabPlaceAnimal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LblWhereSending.setFont(new java.awt.Font("Berlin Sans FB Demi", 2, 36)); // NOI18N
        LblWhereSending.setForeground(new java.awt.Color(204, 204, 204));
        LblWhereSending.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LblWhereSending.setText("Where are you Sending the Patient");
        LblWhereSending.setPreferredSize(new java.awt.Dimension(280, 42));
        tabPlaceAnimal.add(LblWhereSending, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 730, 100));

        pnlPlacePet.setBackground(new java.awt.Color(153, 153, 153));
        pnlPlacePet.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlPlacePet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdoBtnSendSurgery.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupSend.add(rdoBtnSendSurgery);
        rdoBtnSendSurgery.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        rdoBtnSendSurgery.setText("Send to Surgery");
        rdoBtnSendSurgery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnSendSurgeryActionPerformed(evt);
            }
        });
        pnlPlacePet.add(rdoBtnSendSurgery, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 70));

        rdoBtnSendGrooming.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupSend.add(rdoBtnSendGrooming);
        rdoBtnSendGrooming.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        rdoBtnSendGrooming.setText("Send to Grooming");
        rdoBtnSendGrooming.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnSendGroomingActionPerformed(evt);
            }
        });
        pnlPlacePet.add(rdoBtnSendGrooming, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 70));

        rdoBtnSendWaiting.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupSend.add(rdoBtnSendWaiting);
        rdoBtnSendWaiting.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        rdoBtnSendWaiting.setText("Send to Waiting Room");
        rdoBtnSendWaiting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnSendWaitingActionPerformed(evt);
            }
        });
        pnlPlacePet.add(rdoBtnSendWaiting, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 290, 70));

        rdoBtnSendCheckup.setBackground(new java.awt.Color(153, 153, 153));
        buttonGroupSend.add(rdoBtnSendCheckup);
        rdoBtnSendCheckup.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 24)); // NOI18N
        rdoBtnSendCheckup.setText("Send to Dr.'s Office");
        rdoBtnSendCheckup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBtnSendCheckupActionPerformed(evt);
            }
        });
        pnlPlacePet.add(rdoBtnSendCheckup, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 290, 70));

        tabPlaceAnimal.add(pnlPlacePet, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 360, 330));

        tabPanelEmp.addTab("Place Animal", tabPlaceAnimal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanelEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPanelEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tabPanelEmp.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("Employee Menu");

        setSize(new java.awt.Dimension(914, 707));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnterPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterPinActionPerformed
        if (String.valueOf(PasswordEmployee.getPassword()).equals("1661")){
            LblUserID.setVisible(true);
            PasswordUserID.setVisible(true);
            btnEnterUserID.setVisible(true);
            
            PasswordEmployee.setText("");
            
            tabBilling.setEnabled(true);
            tabInventory.setEnabled(true);
            tabPlaceAnimal.setEnabled(true);
            tabReport.setEnabled(true);
            tabSchedule.setEnabled(true);
            tabUpdatePt.setEnabled(true);
        }
        else{
            JOptionPane.showMessageDialog(this, "Pin is incorrect, please try again");
        }
    }//GEN-LAST:event_btnEnterPinActionPerformed

    private void rdoBtnSurgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnSurgeryActionPerformed
        calendar = clinic.surgeryCalendar;
    }//GEN-LAST:event_rdoBtnSurgeryActionPerformed

    private void rdoBtnGroomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnGroomingActionPerformed
        calendar = clinic.groomingCalendar;
    }//GEN-LAST:event_rdoBtnGroomingActionPerformed

    private void rdoBtnCheckupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnCheckupActionPerformed
        calendar = clinic.checkupCalendar;
    }//GEN-LAST:event_rdoBtnCheckupActionPerformed

    private void btnEnterTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterTimeActionPerformed
        try{
            String date = (String.valueOf(spinnerTime.getValue()));
            System.out.println(date);
            String[] MDY = date.split(" ");
            String month = MDY[1];
            int day = Integer.parseInt(MDY[2]);
            String time = MDY[3];
            String[] HM = time.split(":");
            int hour = Integer.parseInt(HM[0]);

            int min = Integer.parseInt(HM[1]);

            if(jCheckBoxSchedule.isSelected()){
                if(calendar.Schedule(current_animal, month, day, hour)){

                    JOptionPane.showMessageDialog(this,"Your appointment was successfully scheduled!");
                }
                else{

                    JOptionPane.showMessageDialog(this,"Appointment not available, try another date or time");
                }
            }
            else if(jCheckBoxCancel.isSelected()){
                if(calendar.deleteApt(current_animal, month, day, hour)){

                    JOptionPane.showMessageDialog(this,"Your appointment was successfully cancelled!");
                }
                else{

                    JOptionPane.showMessageDialog(this,"Appointment does not exist, \nverify date or time and try again");
                }
            }
        
        }
        catch(NullPointerException e){
            JOptionPane.showMessageDialog(this,"Ensure Customer ID has been entered and\n both a treatment and schedule option\n are selected before clicking enter.");
        }
    }//GEN-LAST:event_btnEnterTimeActionPerformed

    private void btnCheckInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckInventoryActionPerformed
        TxtAreaInventory.setText(clinic.inventory.checkInventory());
    }//GEN-LAST:event_btnCheckInventoryActionPerformed

    private void btnPayBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayBillActionPerformed
        pnlPay.setVisible(true);
        
        
    }//GEN-LAST:event_btnPayBillActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        Transaction billPay = new Transaction();
        billPay.billPaid(current_owner, current_owner.getBill(), Integer.parseInt(TxtDesired.getText()));
        
        TxtStillOwed.setText(String.valueOf(current_owner.getBill()));
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
        
        //generates a current year to date report in the field
        TxtAreaReport.setText(clinic.transactions.getReport());
    }//GEN-LAST:event_btnGenerateActionPerformed

    private void TxtStillOwedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtStillOwedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtStillOwedActionPerformed

    private void btnSubmitMedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMedsActionPerformed
        clinic.transactions.purchaseMeds(clinic.inventory, (int) spinnerMeds.getValue());
    }//GEN-LAST:event_btnSubmitMedsActionPerformed

    private void btnSubmitOfficeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitOfficeActionPerformed
        clinic.transactions.purchaseOffice(clinic.inventory, (int) spinnerOffice.getValue());
    }//GEN-LAST:event_btnSubmitOfficeActionPerformed

    private void btnSubmitMedSupplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitMedSupplyActionPerformed
        clinic.transactions.purchaseSupply(clinic.inventory, (int) spinnerMedSupply.getValue());
    }//GEN-LAST:event_btnSubmitMedSupplyActionPerformed

    private void btnSubmitGroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitGroomActionPerformed
        clinic.transactions.purchaseGroom(clinic.inventory, (int) spinnerGroom.getValue());
    }//GEN-LAST:event_btnSubmitGroomActionPerformed

    private void rdoBtnSendGroomingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnSendGroomingActionPerformed
        clinic.sendGrooming(current_animal);
        JOptionPane.showMessageDialog(this, "Pt. is being groomed");
    }//GEN-LAST:event_rdoBtnSendGroomingActionPerformed

    private void rdoBtnSendWaitingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnSendWaitingActionPerformed
        clinic.sendWaiting(current_animal);
        JOptionPane.showMessageDialog(this, "Pt is in the waiting room");
    }//GEN-LAST:event_rdoBtnSendWaitingActionPerformed

    private void rdoBtnSendCheckupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnSendCheckupActionPerformed
        clinic.sendDrOffice(current_animal);
        JOptionPane.showMessageDialog(this, "Pt. is being seen by the Doctor");
    }//GEN-LAST:event_rdoBtnSendCheckupActionPerformed

    private void btnEnterUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterUserIDActionPerformed
        if(clinic.registry.searchByOwner(String.valueOf(PasswordUserID.getPassword())) != null){
            JOptionPane.showMessageDialog(this,"Profile found, ensure info is correct in update Pt info tab"); 
            current_owner = clinic.registry.searchByOwner(String.valueOf(PasswordUserID.getPassword()));
            current_animal = current_owner.getAnimal();
            
            TxtCurrentBill.setText(String.valueOf(current_owner.getBill()));
            
            TxtCustName.setText(current_owner.getName());
            TxtCustDOB.setText(current_owner.getDOB());
            TxtCustPhone.setText(current_owner.getPhoneNumber());
            TxtCurrentBill.setText(String.valueOf(current_owner.getBill()));
                
            TxtPetName.setText(current_animal.getName());
            TxtPetAge.setText(String.valueOf(current_animal.getAge()));
            TxtPetSpecies.setText(current_animal.getSpecies());
            TxtPetBreed.setText(String.valueOf(current_animal.getBreed()));
        }
        else{
            JOptionPane.showMessageDialog(this,"Profile not found, ensure user ID is correct");
        }
    }//GEN-LAST:event_btnEnterUserIDActionPerformed

    private void btnUpdateOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOwnerActionPerformed
        String userID = TxtCustUserID.getText();
        String owner_name = TxtCustName.getText();
        String DOB = TxtCustDOB.getText();
        String phone = TxtCustPhone.getText();
        
        String animal_name = TxtPetName.getText();
        int animal_age = Integer.parseInt(TxtPetAge.getText());
        String species = TxtPetSpecies.getText();
        String breed = TxtPetBreed.getText();
        
        // Updates the value for that id
        addOwner(userID, owner_name, DOB, phone);
        ownerRW.updateCSV();
        
        addAnimal(animal_name, animal_age, species, breed);
        animalRW.updateCSV();
        
        
        JOptionPane.showMessageDialog(this, "Information Updated");
        
        TxtCustUserID.setText("");
        TxtCustName.setText("");
        TxtCustDOB.setText("");
        TxtCustPhone.setText("");
        
        TxtPetName.setText("");
        TxtPetAge.setText("");
        TxtPetSpecies.setText("");
        TxtPetBreed.setText("");
        //set animal text
        
    }//GEN-LAST:event_btnUpdateOwnerActionPerformed

    private void btnAddAllergiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAllergiesActionPerformed
        current_animal.allergies.add(TxtPetAllergies.getText());
    }//GEN-LAST:event_btnAddAllergiesActionPerformed

    private void btnAddMedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMedsActionPerformed
        current_animal.medications.add(TxtPetMeds.getText());
    }//GEN-LAST:event_btnAddMedsActionPerformed

    private void btnAddNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNotesActionPerformed
        current_animal.drNotes.add(TxtPetNotes.getText());
    }//GEN-LAST:event_btnAddNotesActionPerformed

    private void rdoBtnSendSurgeryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBtnSendSurgeryActionPerformed
        clinic.sendSurgery(current_animal);
        JOptionPane.showMessageDialog(this, "Pt. Prepping for Surgery");
    }//GEN-LAST:event_rdoBtnSendSurgeryActionPerformed

    
//    private void removeOwner(String userID)
//    {
//        //removes cusomter from registry
//        clinic.registry.removeOwner(userID);
//        
//    }
//    
//    private void removeAnimal(String name)
//    {
//        //removes customer from registry
//        clinic.registry.removePet(name);
//        
//    }
    
    /**
     * Creates and returns a new Animal patient
     * @param name
     * @param age
     * @param species
     * @param breed
     */
    public void addAnimal(String name, int age, String species, String breed){
        //creates and returns animal object using entered user info
        
        try{
            current_animal = new Animal(name, age, species, breed);
        
            //adds animal to animal registry
            clinic.registry.addPT(current_animal.getName(), current_animal); //adds animal to animal registry
            current_owner.setAnimal(current_animal);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getCause());
        }
        
    }
    
    /**
     * Method adds owner and animal customers to their respective registry and
     * assigns them to each other. 
     * @param userID owners user ID used to search for them in the registry
     * @param name
     * @param dob
     * @param phone
     */
    public void addOwner(String userID, String name, String dob, String phone){
        
        try{
            
            current_owner = new Owner(userID, name, dob, phone);

            clinic.registry.addCustomer(userID, current_owner);  //adds owner to owner registry
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getCause());
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("DarkMetal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeMenu(clinic).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LblCustDOB;
    private javax.swing.JLabel LblCustName;
    private javax.swing.JLabel LblCustPhone;
    private javax.swing.JLabel LblCustUserID;
    private javax.swing.JLabel LblGrooming;
    private javax.swing.JLabel LblMedSupply;
    private javax.swing.JLabel LblMedications;
    private javax.swing.JLabel LblOffice;
    private javax.swing.JLabel LblOrder;
    private javax.swing.JLabel LblPetAge;
    private javax.swing.JLabel LblPetAllergies;
    private javax.swing.JLabel LblPetBreed;
    private javax.swing.JLabel LblPetMeds;
    private javax.swing.JLabel LblPetName;
    private javax.swing.JLabel LblPetNotes;
    private javax.swing.JLabel LblPetSpecies;
    private javax.swing.JLabel LblPin;
    private javax.swing.JLabel LblUserID;
    private javax.swing.JLabel LblWhereSending;
    private javax.swing.JPasswordField PasswordEmployee;
    private javax.swing.JPasswordField PasswordUserID;
    private javax.swing.JPanel PnlOrderMore;
    private javax.swing.JTextArea TxtAreaInventory;
    private javax.swing.JTextArea TxtAreaReport;
    private javax.swing.JTextField TxtCurrentBill;
    private javax.swing.JTextField TxtCustDOB;
    private javax.swing.JTextField TxtCustName;
    private javax.swing.JTextField TxtCustPhone;
    private javax.swing.JTextField TxtCustUserID;
    private javax.swing.JTextField TxtDesired;
    private javax.swing.JTextField TxtPetAge;
    private javax.swing.JTextField TxtPetAllergies;
    private javax.swing.JTextField TxtPetBreed;
    private javax.swing.JTextField TxtPetMeds;
    private javax.swing.JTextField TxtPetName;
    private javax.swing.JTextField TxtPetNotes;
    private javax.swing.JTextField TxtPetSpecies;
    private javax.swing.JTextField TxtStillOwed;
    private javax.swing.JButton btnAddAllergies;
    private javax.swing.JButton btnAddMeds;
    private javax.swing.JButton btnAddNotes;
    private javax.swing.JButton btnCheckInventory;
    private javax.swing.JButton btnEnterPin;
    protected javax.swing.JButton btnEnterTime;
    private javax.swing.JButton btnEnterUserID;
    private javax.swing.JButton btnGenerate;
    private javax.swing.JButton btnPay;
    private javax.swing.JButton btnPayBill;
    private javax.swing.JButton btnSubmitGroom;
    private javax.swing.JButton btnSubmitMedSupply;
    private javax.swing.JButton btnSubmitMeds;
    private javax.swing.JButton btnSubmitOffice;
    private javax.swing.JButton btnUpdateOwner;
    private javax.swing.ButtonGroup buttonGroupAptOption;
    private javax.swing.ButtonGroup buttonGroupCalendar;
    private javax.swing.ButtonGroup buttonGroupSend;
    private javax.swing.ButtonGroup buttonGroupUpdate;
    private javax.swing.JCheckBox jCheckBoxCancel;
    private javax.swing.JCheckBox jCheckBoxSchedule;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCurrentBill;
    private javax.swing.JLabel lblDesired;
    private javax.swing.JLabel lblSelectAptOption;
    private javax.swing.JLabel lblSelectDate;
    private javax.swing.JLabel lblSelectTreat;
    private javax.swing.JLabel lblStillOwed;
    private javax.swing.JLabel lblThenPush;
    private javax.swing.JPanel pnlAddAnimalInfo;
    private javax.swing.JPanel pnlCurrentBill;
    private javax.swing.JPanel pnlPay;
    private javax.swing.JPanel pnlPlacePet;
    private javax.swing.JPanel pnlScheduleorCancel;
    private javax.swing.JPanel pnlTrtBtn;
    private javax.swing.JPanel pnlUpdateOwner;
    private javax.swing.JRadioButton rdoBtnCheckup;
    private javax.swing.JRadioButton rdoBtnGrooming;
    private javax.swing.JRadioButton rdoBtnSendCheckup;
    private javax.swing.JRadioButton rdoBtnSendGrooming;
    private javax.swing.JRadioButton rdoBtnSendSurgery;
    private javax.swing.JRadioButton rdoBtnSendWaiting;
    private javax.swing.JRadioButton rdoBtnSurgery;
    private javax.swing.JSpinner spinnerGroom;
    private javax.swing.JSpinner spinnerMedSupply;
    private javax.swing.JSpinner spinnerMeds;
    private javax.swing.JSpinner spinnerOffice;
    private javax.swing.JSpinner spinnerTime;
    private javax.swing.JPanel tabBilling;
    private javax.swing.JPanel tabInventory;
    private javax.swing.JTabbedPane tabPanelEmp;
    private javax.swing.JPanel tabPlaceAnimal;
    private javax.swing.JPanel tabReport;
    private javax.swing.JPanel tabSchedule;
    private javax.swing.JPanel tabSignIn;
    private javax.swing.JPanel tabUpdatePt;
    // End of variables declaration//GEN-END:variables
}
